TAG: 'CARLA_perception'

GPUS: [0, 1, 2, 3, 4, 5, 6, 7]
# GPUS: [7]

BATCHSIZE: 1
BACKWARDNUM: 1
PRECISION: 32
EPOCHS: 20

N_WORKERS: 8

DATASET:
  NAME: 'carla'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 0

IMAGE:
  FINAL_DIM: (224, 400)
  ORIGINAL_HEIGHT: 448
  ORIGINAL_WIDTH: 800

LIFT:
  X_BOUND: [-32.0, 32.0, 0.25]
  Y_BOUND: [-32.0, 32.0, 0.25]
  D_BOUND: [0.0, 32.0, 1.0]
  GT_DEPTH: False

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: True
  HDMAP:
    ENABLED: True

INSTANCE_SEG:
  ENABLED: False

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: False

PLANNING:
  ENABLED: False

OPTIMIZER:
  LR: 1e-3


