TAG: 'CARLA_planning'

GPUS: [0, 1, 2, 3, 4, 5, 6, 7]

BATCHSIZE: 1
BACKWARDNUM: 1
PRECISION: 32
EPOCHS: 20

N_WORKERS: 8

DATASET:
  NAME: 'carla'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

IMAGE:
  FINAL_DIM: (224, 400)
  ORIGINAL_HEIGHT: 448
  ORIGINAL_WIDTH: 800

LIFT:
  X_BOUND: [-50.0, 50.0, 0.5]
  Y_BOUND: [-50.0, 50.0, 0.5]
  D_BOUND: [0.0, 50.0, 1.0]
  GT_DEPTH: False

EGO:
  WIDTH: 2.12
  HEIGHT: 4.90

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: True
  HDMAP:
    ENABLED: True

INSTANCE_SEG:
  ENABLED: False

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: True
  METHOD: 'GAUSSIAN'

PLANNING:
  ENABLED: True
  GRU_STATE_SIZE: 128
  SAMPLE_NUM: 2400

FUTURE_DISCOUNT: 0.95

OPTIMIZER:
  LR: 2e-4

COST_FUNCTION:
  SAFETY: 1.
  HEADWAY: 1.
  LRDIVIDER: 10.
  COMFORT: 1.
  PROGRESS: 1.
  VOLUME: 100.


PRETRAINED:
   LOAD_WEIGHTS: True
